# Site settings
title: CH EN Fall 2025 Schedule Planner
description: The filters below offer course or instructor views of the schedule this semester.
theme: jekyll-theme-cayman
show_downloads: false
