# Site settings
title: CHEN-F25 - Chemical Engineering in the Kitchen
description: A course exploring the principles of chemical engineering through the lens of cooking and food preparation.
theme: jekyll-theme-minimal
